### ISSUE TITLE
Having generated masks appear as annotations in Qupath? 

### ISSUE THREAD

**Issue by penguingiraffe2** [tpecot/WholeSlideImageAnalysisWithQuPath#1]
How can I make the masks generated by your code into annotations in qupath? Thanks so much!

**Comment by tpecot** [comment]
Normally, you shouldn't  need to convert the masks into annotations as you should be able to extract measurements or apply classifications to your detections. However, it is possible to convert detections into annotations by using a script:
def class_for_detections = getPathClass('current_class')
def current_detections = getDetectionObjects()
def newAnnotations = current_detections.collect {
    return PathObjects.createAnnotationObject(it.getROI(), it.getPathClass())
}
newAnnotations.eachWithIndex { annotation , i ->
    annotation.setPathClass(class_for_detections)
}
removeObjects(current_detections, true)
addObjects(newAnnotations)
